services:
  db:
    image: postgres:18
    restart: always 
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} 
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_DB=${POSTGRES_DB} 

  backend:
    restart: always
    image: ${BACKEND_REPO}
    environment:
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGHOST=${POSTGRES_HOST}
      - PGDATABASE=${POSTGRES_DB}
      - JWT_SECRET=${BACKEND_JWT_SECRET}
      - JWT_RT_TTL=${BACKEND_JWT_RT_TTL}
      - CORS_ALLOWED=${BACKEND_CORS_ALLOWED}
    ports:
      - ${BACKEND_PORT}
    depends_on:
      - db

  frontend:
    restart: always
    image: ${FRONTEND_REPO}
    environment:
      - VITE_API_URL=${FRONTEND_VITE_API_URL}
    ports:
      - ${FRONTEND_PORT}